### ISSUE TITLE
На 32-битных Ubuntu большинство горячих клавиш в SCg-редакторе работает только при запуске под root

### ISSUE THREAD

**Issue by rusetski-k** [ostis-dev/kbe#387]
Работают всегда только 1..9

**Comment by rusetski-k** [comment]
похоже, что проблема в пакете appmenu-qt5 -- https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1313248
во всяком случае, после его удаления проблема исчезла

**Comment by Osyotr** [comment]
Ubuntu 16.04.1 x64, та же проблема.
Удаление appmenu-qt5 помогло.

**Comment by deniskoronchik** [comment]
Test on different OS:
* [x] Ubuntu 16.04.01 64bit
* [ ] Windows
* [ ] Ubuntu 32Bit ?
